# Learning Statistics from Scratch with the MPG Dataset

## Introduction

Welcome! This notebook is designed to guide you through the fundamental concepts of statistics, from the very basics to more advanced inferential techniques. All concepts will be illustrated using the **MPG (Miles Per Gallon) dataset** from the `seaborn` library, which contains fuel economy and performance data for various car models.

**Why statistics?**  
Statistics is the science of collecting, analyzing, interpreting, and presenting data. In a world driven by data, having a solid grasp of statistics empowers you to make informed decisions, uncover patterns, and test hypotheses.

**What you will learn:**  
- Descriptive statistics: central tendency, dispersion, and visualization.  
- Probability fundamentals and distributions.  
- Inferential statistics: confidence intervals and hypothesis testing.  
- Regression analysis to model relationships.

**Let's dive in!**

In [ ]:
# Import necessary libraries for data analysis and visualization
import numpy as np  # For numerical operations and array manipulation
import pandas as pd  # For data manipulation and analysis
import matplotlib.pyplot as plt  # For creating static, animated, and interactive visualizations
import seaborn as sns  # For statistical data visualization based on matplotlib
from scipy import stats  # For scientific computing and statistical analysis
import warnings  # For warning control
warnings.filterwarnings('ignore')  # Ignore all warning messages to keep the output clean

# Set style for plots to improve visualization aesthetics
sns.set_style("whitegrid")  # Set the style of seaborn plots to whitegrid
plt.rcParams['figure.figsize'] = (10, 6)  # Set default figure size for matplotlib plots to 10x6 inches

1. The MPG Dataset
First, let's load the dataset and get an overview.

In [ ]:
# Load the dataset from seaborn library
# The 'mpg' dataset contains fuel efficiency data for various cars
mpg = sns.load_dataset('mpg')
# Display the first 5 rows of the dataset
# This provides a quick overview of the data structure and contents
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:

# Check structure and missing values
# Display information about the mpg dataset
mpg.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [10]:
# Load the dataset from seaborn's built-in datasets
# The 'mpg' dataset contains fuel efficiency data for various cars
mpg = sns.load_dataset('mpg')
# Display the first 5 rows of the dataset
# This gives us a quick overview of the data structure and values
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [12]:
# Drop rows with missing values (for simplicity)
# This line removes any rows that contain NaN (Not a Number) values in the dataset
# It's a simple approach to handle missing data, which may not be optimal for all cases
mpg_clean = mpg.dropna()
# Print the number of original rows and the number of rows after cleaning
# This helps to understand how much data was lost in the cleaning process
print(f"Original rows: {len(mpg)}, Clean rows: {len(mpg_clean)}")
# Display the first 5 rows of the cleaned dataset
# This provides a quick preview of the cleaned data
mpg_clean.head()

Original rows: 398, Clean rows: 392

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
# Drop rows with missing values (for simplicity)
# This line removes any rows in the 'mpg' DataFrame that contain NaN (missing) values
# The result is stored in a new DataFrame called 'mpg_clean'
mpg_clean = mpg.dropna()
# Print the original number of rows and the number of rows after cleaning
# This helps to understand how many data points were removed due to missing values
print(f"Original rows: {len(mpg)}, Clean rows: {len(mpg_clean)}")
# Display the first 5 rows of the cleaned DataFrame
# This provides a quick preview of the data after the cleaning process
mpg_clean.head()

Original rows: 398, Clean rows: 392

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

Dataset Description:

mpg: miles per gallon (target variable)

cylinders: number of cylinders

displacement: engine displacement (cubic inches)

horsepower: engine horsepower

weight: vehicle weight (lbs)

acceleration: time to accelerate from 0 to 60 mph (seconds)

model_year: year of manufacture (modulo 100)

origin: country of origin (USA, Europe, Japan)

name: car model name

We'll use mpg_clean for all analyses.

2. Basic Statistical Concepts
2.1 Population vs. Sample
Population: All cars ever made (or all cars of a certain type).

Sample: Our dataset, which is a subset of all cars. We'll use sample statistics to infer population parameters.

2.2 Types of Variables
Quantitative (numerical):

Continuous: e.g., mpg, weight, acceleration.

Discrete: e.g., cylinders, model_year.

Categorical (qualitative): e.g., origin, name (though name is unique).

2.3 Descriptive vs. Inferential Statistics
Descriptive: Summarize and describe the data (mean, median, variance, plots).

Inferential: Make predictions or generalizations about a population based on sample data (hypothesis tests, confidence intervals).

3. Descriptive Statistics
3.1 Measures of Central Tendency
Mean: The average value.
Median: The middle value when sorted.
Mode: The most frequent value.

Let's compute these for mpg (fuel efficiency).

In [15]:
# Central tendency for mpg
mean_mpg = np.mean(mpg_clean['mpg'])
median_mpg = np.median(mpg_clean['mpg'])
mode_mpg = stats.mode(mpg_clean['mpg'])[0][0]  # scipy mode returns array

print(f"Mean MPG: {mean_mpg:.2f}")
print(f"Median MPG: {median_mpg:.2f}")
print(f"Mode MPG: {mode_mpg}")

IndexError: invalid index to scalar variable.